name: Push - Create & Tag Protobuf - Go

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
          check-latest: false
          cache: true
      - name: Generate Go Source
        shell: bash
        run: |
          make pipeline-build
      - name: Generate Go Gateway source
        shell: bash
        run: |
          make pipeline-build-gateway
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(protobuf-go) : Auto-generated by Github Action"
          tagging_message: ${{ steps.tag_version.outputs.new_tag }}
          file_pattern: "protogen/*"
